version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jenkin_nextjs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql_nextjs

volumes:
  db_data:
